db/urls.py
from django.urls import path
from . import views

app_name="db"

urlpatterns = [
    path('login/', views.db_login),
    path('fuck/', views.fuck, name='fuck'),
    path('index01/', views.firstindex)

]

dj_01/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('db/', include('db.urls'))
]

news/urls.py
from django.urls import path
from . import views
app_name="news"

urlpatterns = [
    path('list/', views.news_list,name='newslist'),
    path('id/<newsid>/', views.news_id,name='newsid'),
    path('search/', views.news_search,name='search'),
    path('tpmif/', views.tpm_if,name='tpmif'),
    path('tpmfor/', views.tpm_for,name='tpmfor'),
    path('addview/', views.add_view,name='addview'),
    path('cut/', views.cut_view,name='cut'),
    path('date/', views.date_view,name='date'),
    path('', views.dtlurl)
]

db/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

db/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect,reverse
# Create your views here.

def db_login(request):
	username = request.GET.get('username')
	if username:
		return HttpResponse("gogo")
	else:
		rev=reverse('db:fuck')
		print ("="*20)
		print (rev)
		print ("="*20)
		return redirect(rev)

def fuck(request):
	return HttpResponse("Fuck you!")

def firstindex(request):
	return render(request,'index.html')

news/views.py
from django.shortcuts import render
from datetime import datetime

from django.http import HttpResponse


# Create your views here.
def news_list(request):
	return HttpResponse("新闻列表")

def news_id(request,newsid):			#通过url中指定某段直接传递newsid
	nid="Your news id is %s" % newsid
	return HttpResponse(nid)

def news_search(request):				#通过?keys=xxx来传递keys
	keys=request.GET.get('keys')
	newss="Your search news is %s" % keys
	return HttpResponse(newss)

#DTL test if 同时进行Django参数传递测试
def tpm_if(request):
	context={"tpm":"This is DTL parameter test!","names":["wangsp","Jane"],"age":16}
	return render(request,'DTL_if.html',context=context)

#DTL test for
def tpm_for(request):
	context={
	"books":[
	{"name":"将夜","price":99},
	{"name":"幽梦","price":78},
	{"name":"黑切","price":109}
	],
	"students":{"01":70,"02":32,"03":98}
	}
	return render(request, 'DTL_for.html', context=context)

#DTL test url parameter
def dtlurl(request):
	return render(request, 'DTL_url.html')

#add过滤器拼接测试
def add_view(request):
	context={
	"value1":["1",2,"3m"],
	"value2":["A","b","ZY"]
	}
	return render(request, 'testadd.html',context=context)

#cut过滤器删除测试
def cut_view(request):
	return render(request, 'testcut.html')

#date过滤器删除测试
def date_view(request):
	context={
		'now':datetime.now()
	}
	return render(request, 'date.html',context=context)

templates/DTL_for.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>Title</title>
</head>

<body>
	<ul>
		{%for book in books %}
			<li>{{book}}</li>
		{%endfor%}
	</ul>

	<ul>遍历一个dict
		{%for key,value in students.items %}
			<li>{{key}}/{{value}}</li>
		{%endfor%}
	</ul>
	
	<table>
		<thead>
			<tr>
				<td>序号2007649609</td>
				<td>书名</td>
				<td>价格</td>
			</tr>
		</thead>
		<tbody>
				{%for book in books %}
				    {%if forloop.first%}
						<tr style="background: green">
					{%elif forloop.last%}
						<tr style="background: pink">
					{%else%}
						<tr>
					{%endif%}
						<td>{{forloop.counter}}</td>		<!forloop.counter用于计算遍历的次数>
						<td>{{book.name}}</td>
						<td>{{book.price}}</td>
					</tr>
				{%endfor%}
		</tbody>
	</table>

</body>
</html>

templates/DTL_if.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>Title</title>
</head>

<body>

	{{ names.0 }}			#无论是dict还是list，都是通过.去获取参数
	<p>{{ tpm }}</p>
	{%if age < 18 %}
		<p> Get out!!! </p>
	{%else %}
		<p> Welcome!!! </p>
	{%endif%}

</body>
</html>

templates/DTL_url.html
{% extends 'base.html' %}

{% block test1 %}

<body>
	<ul>
		<li><a href="{% url 'news:newslist' %}">正常测试-新闻列表</a></li>
		<li><a href="{% url 'news:newsid' newsid='XXX' %}">url中指定参数-新闻ID</a></li>
		<li><a href="{% url 'news:search' %}?keys=XXX">url非指定参数-搜索新闻</a></li>
		<li><a href="{% url 'news:tpmif' %}">DTL中if测试</a></li>
		<li><a href="{% url 'news:tpmfor' %}">DTL中for测试</a></li>
		<li><a href="{% url 'news:addview' %}">add拼接测试</a></li>
		<li><a href="{% url 'news:cut' %}">cut测试</a></li>
		<li><a href="{% url 'news:date' %}">DTL中date过滤器测试</a></li>
	</ul>
	<!--第一种加载静态文件的方法,通过url调用-->
	<img src="/static/news/first.jpg">
	<!--第二种加载静态文件的方法,通过url调用-->
	<img src="{% static 'news/sec.jpg' %}">
</body>
{% endblock %}

templates/base.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>Title</title>
	<style>
		body {background: pink}
	</style>
</head>

<div class="content">			<!--用于父模板继承测试-->
	{% block test1 %}
	{% endblock %}
</div>

</html>

templates/date.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>date过滤器测试</title>
</head>

<body>
	<ul>
		<li>date过滤器测试:{{ now|date:"Y-M-d H-i-s" }}</li>

	</ul>
</body>
</html>

templates/index.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>Title</title>
	<link rel="stylesheet" type="text/css" href="{%static 'pink_bg.css'%}">
</head>

<body>
	我的第一个Django HTML模板
	<img src="{%static 'db/profile.jpg'%}">
	<img src="{%static '12win.png'%}">
</body>
</html>

templates/testadd.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>add拼接参数</title>
</head>

<body>
	<ul>
		<li>add拼接测试int:{{1|add:2}}</li>
		<li>add拼接测试str:{{"1"|add:"2c"}}</li>
		<li>add拼接测试列表传递:{{value1|add:value2}}</li>
	</ul>
</body>
</html>

templates/testcut.html
<!First Template>
<html lan="en">
<head>
	<meda charset="UTF-8">
	<title>cut过滤器测试</title>
</head>

<body>
	<ul>
		<li>cut过滤器测试:{{"Hi My name is wsp and you"|cut:" "}}</li>

	</ul>
</body>
</html>